import type { Metadata } from "next";
import { AuthProvider } from "./AuthProvider";
import Sidebar from "./components/Sidebar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>
          <AuthProvider>
            <Sidebar />
          </AuthProvider>
        </div>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
